const UPDATE_GROUP_NAME = "UPDATE_GROUP_NAME";
const CREATE_GROUP = "CREATE_GROUP";
const UPDATE_GROUP_USER = "UPDATE_GROUP_USER";

module.exports = { UPDATE_GROUP_NAME, CREATE_GROUP, UPDATE_GROUP_USER };
